---
- hosts: single
  become: yes
  tasks:
    - name: install mysql
      yum: name=mysql-server state=absent


    - name: install python-mysql
      yum: name=MySQL-python state=absent



    - name: install libselinux
      yum: name=libselinux-python state=absent


#    - name: start mysql service
#      service: name=mysqld state=started


#    - name: Try login mysql as root with default empty password
#      mysql_variables: login_user=root login_password='' variable=version




















#    - name: Copy the ".my.cnf" file
#      template: src=my.cnf.j2 dest=~/.my.cnf mode=0600

    
#    - name: Set the root user for MYSQL
#      mysql_user: name=root password={{ mysql_password }}
