---
- hosts: single
  become: yes
  tasks: 
   - name: install mysql packages
     yum:
      name: "{{item}}"
      state: absent
     with_items:
       - mariadb-server
       - MySQL-python
   
   - name: start mariadb service
     service:
       name: mariadb
       state: started


   - name: Create wordpress db
     mysql_db:
       name: "wordpress"
       login_user: root
       state: absent

   - name: Create wordpress user
     mysql_user:
        name:     "wordpress"
        password: "rp6w9rMM!A"
        priv:     "wordpress.*:ALL"
        login_user: root
        state: absent


